name: Release

on:
   workflow_run:
      workflows:
       # TODO: remove this item. It is just here to iterate quickly
       - Unit tests
       - Integration tests
      branches: [master]
      types:
       - completed

jobs:
   release-image-to-docker-hub:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      steps:
       - name: 'Download artifact'
         uses: actions/github-script@v7
         with:
            script: |
               console.log("--> context: ", context);
